### ISSUE TITLE
Single zone office-Schedule fixed interval failing schema validation

### ISSUE THREAD

**Issue by tanushree04** [ladybug-tools-in2/energy-model-measure#11]
Error message on running https://github.com/ladybug-tools-in2/energy-model-measure/blob/model/spec/files/model_single_zone_office_fixed_interval.json
:  "property '#/rooms/0/properties/energy/people' of type object did not match any of the required schemas."

The allowable schema types for people are null or string.

**Comment by chriswmackey** [comment]
I realized that the reason for this is and we should address it as part of https://github.com/ladybug-tools-in2/energy-model-measure/pull/10#pullrequestreview-308915873

**Comment by chriswmackey** [comment]
I think this has been addressed.
