### ISSUE TITLE
Incorrect assignment of Interior Window Constructions within the ConstructionSet

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools-in2/energy-model-measure#24]
The Interior Window constructions are not being assigned to all interior sub-faces. They are only being assigned to interior operable windows for some reason:

![image](https://user-images.githubusercontent.com/5567574/71526742-42493e80-28a6-11ea-9e7a-583b7fa1071b.png)

**Comment by tanushree04** [comment]
@chriswmackey , I just want to make sure of  the mapping of the aperture constructio types from the energy model schema to OpenStudio objects: 

interior_construction : interior sub surface - fixed window construction
window_construction : exterior sub surface - fixed window construction
skylight_construction :  exterior sub surface - skylight construction 
operable_construction : exterior sub surface - operable window construction

**Comment by chriswmackey** [comment]
It's not a one-to-one mapping between Honeybee objects and OpenStudio objects.  OpenStudio has more constructions in the ConstructionSet than Honeybee does so a single honeybee construction maps to multiple OpenStudio constructions. So it should be as follows:

interior_construction : interior sub surface - fixed window construction, operable window construction, 

window_construction : exterior sub surface - fixed window construction

skylight_construction : exterior sub surface - skylight construction

operable_construction : exterior sub surface - operable window construction

**Comment by chriswmackey** [comment]
I can confirm that this one was fixed by https://github.com/ladybug-tools-in2/energy-model-measure/pull/31
