### ISSUE TITLE
Get rid of the unnecessary duplication between `to_openstuido` and `create_openstudio_object`

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools-in2/energy-model-measure#33]
It was really confusing for me to see these two different methods at first, which seemed to be doing the same thing. Then I realized that the `to_openstudio` method was calling the `create_openstudio_object` method but just adding [a bunch of other calls that aren't currently used at all in the measure](https://github.com/ladybug-tools-in2/energy-model-measure/blob/master/lib/ladybug/energy_model/model_object.rb#L100-L114), essentially just adding inefficiency to every single object that's translated.  I don't know if there's a particular use case that @macumber had in mind when he set up the ladybug gem like this but it's not a situation that we are encountering right now in our use of the measure so I am keen to remove it to make things simpler and cleaner. 

Perhaps the bigger reason for removing it is that I can see this rigid structure of only being able to pass a single model object as an input argument to translate the Ladybug object to OpenStudio could prevent us from adding important functionality in the future where we may want to pass additional arguments for the OpenStudio translation process beyond just the Model. Right now while the ``to_openstudio` method calls the `create_openstudio_object` method, this flexibility does not exist.

So, unless anyone objects, I am going to rename all of the all of the `create_openstudio_object` methodsto simply be `to_openstudio` and just get rid of the `to_openstudio` method on the Model Object class.

**Comment by macumber** [comment]
Looks like to_openstudio does some fancy caching and lookups to avoid creating duplicate objects if they are already in the model.  Create object just makes the object no questions asked.  I guess this isn’t a big issue if you don’t have many ladybug objects that all map to the same osm object and you don’t call to_openstudio on the same ladybug object multiple times.  I doubt this is where your performance bottlenecks are though, I’d suggest profiling to figure that out

**Comment by chriswmackey** [comment]
Thanks @macumber . I have profiled it a bit so far and I found that it only shaves a second off of a 15 -second translation process. So you are right but, as I mentioned, none of these fancy lookups are being used right now in the rest of the repo and this setup is making the input arguments for the `create_openstudio_object` methods pretty inflexible such that we may just want to take it out anyway. I'll leave it in for now and plan to come back to this question later.

**Comment by macumber** [comment]
I'm not saying it should stay, that was set up at the very beginning, if you don't need it by now then it probably is ok to remove :-)

**Comment by chriswmackey** [comment]
Thank you, Dan. After thinking it over and seeing your suggestion, I removed it: https://github.com/ladybug-tools-in2/energy-model-measure/pull/50

This should make the process of creating OpenStudio objects a bit more direct and easier to understand (and therefore hopefully make it easier to maintain/edit in the future).
