### ISSUE TITLE
Cleaner output messages

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools-in2/energy-model-measure#88]
Currently it generates a lot of warning messages about gem and json version when translating the schema model to osm file. Is there a way to provide a cleaner output strings without these warnings?

![image](https://user-images.githubusercontent.com/9031066/79282013-14522f00-7e82-11ea-9e95-e7a33b6886ea.png)

**Comment by tanushree04** [comment]
@MingboPeng These warnings should go away on migrating to using OpenStudio 3.0.0 with the measure.

**Comment by MingboPeng** [comment]
@tanushree04 I am using the OpenStudio 3.0.0 already, if you look at the first line of my screenshot.

**Comment by tanushree04** [comment]
@MingboPeng I got in touch with the OpenStudio team, these warnings are resolved in the lastest release candidate for OS 3.0.0 and should not be there with the official OS 3.0.0 release.

**Comment by MingboPeng** [comment]
@tanushree04 thanks for updates!

**Comment by MingboPeng** [comment]
It is confirmed that these warnings have been removed in 3.0.0
