### ISSUE TITLE
Add our own URBANopt Baseline.rb mapper to this repo

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools-in2/energy-model-measure#91]
After I got the chance to talk to Dan Macumber and he explained the original idea for how we would integrate with URBANopt, I am realizing that we should refactor the way that we run this honeybee measure in URBANopt. There are several steps that would be much more streamlined if we just wrote out our own base_workflow.osw and corresponding Baseline.rb mapper rather than using the one that ships with URBANopt by default. For example:

* We could just write out the honeybee JSONs from the interface end and not have to worry about the translation to osm as a separate step. URBANopt SDK could take care of the translation as long as we included the [energy-model-measure](https://github.com/ladybug-tools-in2/energy-model-measure) in the base_workflow.osw.
* We could give the user the ability to customize the measures that went into the base_workflow.osw on the interface end. This would allow them the option of either hard-assigning measure inputs as you would for a single OpenStudio model or use one of the keys in the geoJSON feature file as the input if they so desired. We would just add the users's input to the  base_workflow.osw that is auto-generated by our core libraries and all would be good.

To enable, this, I think we would have to add a Baseline.rb mapper to the energy_model_measure repo. I am thinking that we can add it to the `files` folder so that it still ships with the Ruby gem but it's not a critical element of the `from_honeybee` library.

@tanushree04 ,
Are there any resources that you could point me towards for writing one's own URBANopt mapper? I could just start by deleting stuff out from the Baseline.rb mapper that ships with URBANopt if not.

**Comment by tanushree04** [comment]
@chriswmackey as mentioned in the call, the [Gemfile](https://github.com/urbanopt/urbanopt-example-geojson-project/blob/develop/Gemfile) dictates the gems which gems are installed in the .bundle. 
The URBANopt documentation https://docs.urbanopt.net/customization/modifying_mapper.html has some information on the functionality of the Mapper classes. The best way would be to use the existing mapper class and removing what is not necessary, and add the mapping of the honeybee JSON to the energy model measure argument.

**Comment by chriswmackey** [comment]
It would be very helpful if you can take the first pass at this @tanushree04 .  Thank you, as always.

**Comment by chriswmackey** [comment]
Closing this now that this has been addressed.
